/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Administrator
 */
public class frmGestorVentas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmGestorVentas.class.getName());

    /**
     * Creates new form frmGestorVentas
     */
    public frmGestorVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCaja = new javax.swing.JButton();
        btnCategoria = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        btndatosEnvio = new javax.swing.JButton();
        btnmetodoPago = new javax.swing.JButton();
        btnpedidoVirtual = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnTrabajador = new javax.swing.JButton();
        btnturnoCaja = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("GESTOR MINIMARKET");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        btnCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cajero-automatico.png"))); // NOI18N
        btnCaja.setText("CAJA");
        btnCaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCaja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 130, 110));

        btnCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Categoria.png"))); // NOI18N
        btnCategoria.setText("CATEGORIA");
        btnCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCategoria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 130, 110));

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Clientes.png"))); // NOI18N
        btnCliente.setText("CLIENTE");
        btnCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 130, 110));

        btnVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Ventas.png"))); // NOI18N
        btnVenta.setText("VENTA");
        btnVenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 130, 110));

        btndatosEnvio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/DatosdeEnvio.png"))); // NOI18N
        btndatosEnvio.setText("DATOS DE ENVIO");
        btndatosEnvio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndatosEnvio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btndatosEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 110));

        btnmetodoPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/MetodosDePago (2).png"))); // NOI18N
        btnmetodoPago.setText("METODO DE PAGO");
        btnmetodoPago.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmetodoPago.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnmetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 130, 110));

        btnpedidoVirtual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/PedidoVirtual.png"))); // NOI18N
        btnpedidoVirtual.setText("PEDIDO VIRTUAL");
        btnpedidoVirtual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnpedidoVirtual.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnpedidoVirtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 130, 110));

        btnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Productos.png"))); // NOI18N
        btnProducto.setText("PRODUCTO");
        btnProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 130, 110));

        btnProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Proveedor.png"))); // NOI18N
        btnProveedor.setText("PROVEEDOR");
        btnProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProveedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 130, 110));

        btnTrabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Trabajador.png"))); // NOI18N
        btnTrabajador.setText("TRABAJADOR");
        btnTrabajador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTrabajador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 130, 110));

        btnturnoCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/TurnoDeCaja.png"))); // NOI18N
        btnturnoCaja.setText("TURNO DE CAJA");
        btnturnoCaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnturnoCaja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnturnoCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 130, 110));

        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Usuarios.png"))); // NOI18N
        btnUsuario.setText("USUARIO");
        btnUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 130, 110));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/salida.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 130, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmGestorVentas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCaja;
    public javax.swing.JButton btnCategoria;
    public javax.swing.JButton btnCliente;
    public javax.swing.JButton btnProducto;
    public javax.swing.JButton btnProveedor;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnTrabajador;
    public javax.swing.JButton btnUsuario;
    public javax.swing.JButton btnVenta;
    public javax.swing.JButton btndatosEnvio;
    public javax.swing.JButton btnmetodoPago;
    public javax.swing.JButton btnpedidoVirtual;
    public javax.swing.JButton btnturnoCaja;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
