/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Pc
 */
public class frmTurnoCaja extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmTurnoCaja.class.getName());

    /**
     * Creates new form frmTurnoCaja
     */
    public frmTurnoCaja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbxCaja = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdCaja = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMontoFinal = new javax.swing.JTextField();
        btnCerrarTurno = new javax.swing.JButton();
        btnAbrirTurno = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtMontoInicial = new javax.swing.JTextField();
        cbxCaja1 = new javax.swing.JComboBox<>();
        txtId = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtFechaCierre = new javax.swing.JTextField();
        txtFechaApertura = new javax.swing.JTextField();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("TURNO DE CAJA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Estado:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, -1, -1));

        cbxCaja.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Turno", "Turno Mañana", "Turno Tarde", "Turno Noche" }));
        getContentPane().add(cbxCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("HISTORIAL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 110, -1));

        txtEstado.setText("ABIERTO");
        txtEstado.addActionListener(this::txtEstadoActionPerformed);
        getContentPane().add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 70, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Fecha de cierre:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Monto Inicial:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        txtIdCaja.addActionListener(this::txtIdCajaActionPerformed);
        getContentPane().add(txtIdCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 110, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Monto Final: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        txtMontoFinal.addActionListener(this::txtMontoFinalActionPerformed);
        getContentPane().add(txtMontoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 110, -1));

        btnCerrarTurno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCerrarTurno.setText("CERRAR TURNO");
        btnCerrarTurno.addActionListener(this::btnCerrarTurnoActionPerformed);
        getContentPane().add(btnCerrarTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 180, 70));

        btnAbrirTurno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAbrirTurno.setText("ABRIR TURNO");
        btnAbrirTurno.addActionListener(this::btnAbrirTurnoActionPerformed);
        getContentPane().add(btnAbrirTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 170, 70));

        tablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Caja", "Fecha de Apertura", "Fecha de Cierre", "Monto Inicial", "Monto Final", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaHistorial);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 940, 150));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Fecha de apertura:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        txtMontoInicial.addActionListener(this::txtMontoInicialActionPerformed);
        getContentPane().add(txtMontoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 110, -1));

        cbxCaja1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Tipo de Caja", "Caja Principal", "Recepción", "Caja Virtual" }));
        getContentPane().add(cbxCaja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        txtId.addActionListener(this::txtIdActionPerformed);
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 110, -1));

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 170, 70));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("ID de Caja:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Caja:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("ID:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtFechaCierre.addActionListener(this::txtFechaCierreActionPerformed);
        getContentPane().add(txtFechaCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 110, -1));

        txtFechaApertura.addActionListener(this::txtFechaAperturaActionPerformed);
        getContentPane().add(txtFechaApertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 110, -1));

        btnMenu.setText("MENU");
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 90, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void txtIdCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCajaActionPerformed

    private void txtMontoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoFinalActionPerformed

    private void btnCerrarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarTurnoActionPerformed

    private void btnAbrirTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAbrirTurnoActionPerformed

    private void txtMontoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoInicialActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtFechaCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaCierreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaCierreActionPerformed

    private void txtFechaAperturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaAperturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaAperturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmTurnoCaja().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAbrirTurno;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnCerrarTurno;
    public javax.swing.JButton btnMenu;
    public javax.swing.JComboBox<String> cbxCaja;
    public javax.swing.JComboBox<String> cbxCaja1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaHistorial;
    public javax.swing.JTextField txtEstado;
    public javax.swing.JTextField txtFechaApertura;
    public javax.swing.JTextField txtFechaCierre;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtIdCaja;
    public javax.swing.JTextField txtMontoFinal;
    public javax.swing.JTextField txtMontoInicial;
    // End of variables declaration//GEN-END:variables
}
